# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='cpf',
            field=models.CharField(default=0, max_length=11, unique=True, verbose_name='CPF'),
            preserve_default=False,
        ),
    ]
