# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
