# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_person_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='treatment',
            field=models.CharField(choices=[('a', 'Arq.'), ('aa', 'Arqa.'), ('d', 'Dona'), ('dr', 'Dr.'), ('dra', 'Dra.'), ('e', 'Eng.'), ('ea', 'Engª.'), ('p', 'Prof.'), ('pa', 'Profa.'), ('sr', 'Sr.'), ('sra', 'Sra.'), ('srta', 'Srta.')], default='', max_length=4),
        ),
    ]
