# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_person_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(verbose_name='slug'),
        ),
    ]
