PERSON_DATA = {
    'gender': 'M',
    'treatment': 'sr',
    'first_name': 'Regis',
    'last_name': 'Santos',
    'slug': 'regis-santos',
    'birthday': '1985-12-01 02:42:30+00:00',
    'email': 'regis@example.com',
    'cpf': '75873211795',
    'address': u'Rua São Leopoldo, 101',
    'complement': 'Apto 303',
    'district': u'Belezinho',
    'city': u'São Paulo',
    'uf': 'SP',
    'cep': '03055000',
    'blocked': False,
}
